### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nicolasjund** [wcomartin/kiauvo#1]
Hi, 
I am an french user, a i have an E-niro car.

I'm looking for a way to send the percentage of battery remaining in my Jeedom home automation.
When I saw your GIT I thought it would be possible. But it seems that something is not working.

see below what i done, have you an idea of my mistake, Thanks

pi@KIAUVO:~$ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from KiaUvo import KiaUvo
>>> client = KiaUvo("nicolas.jund@gmail.com", "K**********!")
>>> client.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 44, in login
    self.auth = self.__login(self.username, self.password)
  File "/home/pi/.local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 56, in __login
    return AuthToken(xhr['result']['accessToken'], xhr['result']['refreshToken'])
KeyError: 'result'
>>> client.get_vehicle_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/KiaUvo/__init__.py", line 78, in get_vehicle_list
    raise InvalidAuthException
KiaUvo.InvalidAuthException

**Comment by wcomartin** [comment]
Hi @nicolasjund 

I have found out recently that kia uses a different method for the app in different regions of the world, there is another project being developed that has more progress on this, https://github.com/Hacksore/bluelinky 

this project was originally written for Hyundai but as Hyundai and Kia share a lot of resources, there has been work towards integrating KiaUvo in bluelinky its not ready yet but is being worked on.
